version: "3.7"
services:
  scrape:
    build: .
    command: python bin/01_scrape
    env_file: .env
  alert:
    build: .
    command: bash -c "python bin/02_aggregate && python bin/03_alert"
    env_file: .env
    volumes:
      - "./data:/usr/src/app/data"

volumes:
  data:
