version: "3.7"
services:
  scrape:
    build: .
    command: python bin/01_scrape
    # env_file: .env
    volumes:
      - "./config.json5:/app/config.json5"
  alert:
    build: .
    command: bash -c "python bin/02_aggregate && python bin/03_alert"
    # env_file: .env
    volumes:
      - "./data:/app/data"
      - "./config.json5:/app/config.json5"

volumes:
  data:
