version: "3.1"
services:
  scrape:
    build: .
    command: python bin/01_scrape
    env_file: .env
  alert:
    build: .
    command: python bin/02_aggregate && python bin/03_alert
    env_file: .env
