version: "2.2"
services:
  scraper:
    build: .
    environment:
      STATE: 'Nordrhein-Westfalen'
      CITY: 'Muenster'
      ESTATE_TYPE: 'Haus'
      RENT_TYPE: 'Kauf'
    networks:
      kafka:
networks:
  kafka:
    external: true
    name: kafka-stack-docker-compose_kafka
