name: immoscout

dependencies:
  - python=3.7
  - pip
  - pip:
    # copied from requirements.txt
    - beautifulsoup4~=4.7.1
    - boto3
    - kafka-python~=1.4.6
    - requests~=2.22.0
    - scrapy~=1.6.0
    - toolz~=0.9.0
    # additional dev packages
    - black
    - m2r  # requirement of sphinx
    - pylama
    - Sphinx
    - sphinx_rtd_theme
